FROM maven:3.8-eclipse-temurin-17 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY --from=build /app/target/payment-gateway-1.0.jar ./app.jar
CMD ["java", "-cp", "app.jar", "com.gateway.workers.PaymentWorker"]